package com.example.eam.Enum;


public enum PermissionModule {
    ASSET,
    ASSET_TYPE,
    SERVICE_REQUEST,
    WORK_ORDER,
    WORK_ORDER_TYPE,
    CORRECTIVE_MAINTENANCE,
    PREVENTIVE_MAINTENANCE,
    MATERIAL_REQUISITION,
    PURCHASE_ORDER,
    GOODS_RECEIPT_NOTE,
    VENDOR,
    INVENTORY,
    TECHNICIAN,
    TECHNICIAN_TEAM,
    DASHBOARD,
    REPORTS,
    MANAGE_USERS,
    MANAGE_ROLES,
    INVITE_USER,
    IOT
}

