package com.example.eam.Enum;

public enum SecurityEventType {
    USER_CREATED,
    USER_DISABLED,
    USER_ENABLED,
    USER_DELETED,
    PASSWORD_RESET,
    PASSWORD_CHANGED,
    ROLE_CREATED,
    ROLE_UPDATED,
    USER_ROLE_ASSIGNED,
    USER_ROLE_REMOVED,
    ROLE_PERMISSION_UPDATED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED
}
