flyway.url=${env.SPRING_DATASOURCE_URL}
flyway.user=${env.SPRING_DATASOURCE_USERNAME}
flyway.password=${env.SPRING_DATASOURCE_PASSWORD}
flyway.locations=filesystem:src/main/resources/db/migration
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.cleanDisabled=false
